name 'Subread'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures Subread'
long_description 'Installs/Configures Subread'
version '0.1.0'
